language: node_js

node_js:
  - "12"

script:
  - npm run lint
  - npm test -- --maxWorkers=4
  - npm run build

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules
