version: 2
jobs:
  build:
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: tronin/react-linaria-boilerplate
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ .Branch }}
      - run:
          name: Install packages
          command: yarn install --pure-lockfile
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build project
          command: yarn build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ .Branch }}
          paths:
            - node_modules
  # test:
  #   docker:
  #     - image: tronin/react-linaria-boilerplate
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}-{{ .Branch }}
  #     - run:
  #         name: Test
  #         command: npm test
  #     # - run:
  #     #     name: Generate code coverage
  #     #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
  #     # - store_artifacts:
  #     #     path: test-results.xml
  #     #     prefix: tests
  #     # - store_artifacts:
  #     #     path: coverage
  #     #     prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build
          # filters:
          #   branches:
          #     only: master